"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { RecipeAPIProvider } from "@/hooks/useAPI";

import Navbar from "@/components/navbar";
import Container from "@/components/container";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <RecipeAPIProvider>
          <Container>{children}</Container>
        </RecipeAPIProvider>
      </body>
    </html>
  );
}
